russian_names = {
    'Marital status': 'Семейное положение',
    'Application mode': 'Способ поступления',
    'Application order': 'Порядок поступления',
    'Course': 'Направление',
    'Daytime/evening attendance': 'Форма обучения',
    'Previous qualification': 'Предыдущее образование',
    'Nacionality': 'Национальность',
    "Mother's qualification": 'Образование матери',
    "Father's qualification": "Образование отца",
    "Mother's occupation": "Профессия матери",
    "Father's occupation": "Профессия отца",
    "Displaced": "Миграция",
    "Educational special needs": "Особые потребности",
    "Debtor": "Должник",
    "Tuition fees up to date": "Актуальность оплаты",
    "Gender": "Пол",
    "Scholarship holder": "Стипендия",
    "Age at enrollment": "Возраст при поступлении",
    "International": "Иностранный студент",
    "Units 1 credited": "1 сем перезачтено",
    "Units 1 enrolled": "1 сем планировал",
    "Units 1 evaluations": "1 сем сдавал",
    "Units 1 approved": "1 сем сдал",
    "Units 1 grade": "1 сем средний балл",
    "Units 1 non_eval": "1 сем не сдавал",
    "Units 2 credited": "2 сем перезачтено",
    "Units 2 enrolled": "2 сем планировал",
    "Units 2 evaluations": "2 сем сдавал",
    "Units 2 approved": "2 сем сдал",
    "Units 2 grade": "2 сем средний балл",
    "Units 2 non_eval": "2 сем не сдавал",
    "Unemployment rate": "Уровень безработицы",
    "Inflation rate": "Уровень инфляции",
    "GDP": "ВВП",
    "Target": "Цель"
}